Changes and additions for method-level RPS
SoftEngResearch/emop pull request #79
Opened 2023-09-11 17:12 UTC by mmk-1

This PR adds 4 Mojos which are used for method-level RPS. Each one has a counterpart  for the class-level RPS which is already available.
- Some changes in emop-maven-plugin/pom.xml like updating maven-plugin-plugin which is required for STARTS to run with the latest additions in [this](https://github.com/TestingResearchIllinois/starts/pull/106) PR for STARTS.
- Addition of required dependencies in pom.xml needed for finding method-to-spec mapping.
- MethodHelper.java in utils/ which is required for both method-level and hybrid (seperate PR for later) RPS.

2023-09-11 18:13 UTC, pengyuejiang commented on pom.xml
> +  </dependency>
Please fix the indentations.

2023-09-11 18:16 UTC, pengyuejiang commented on emop-maven-plugin/src/main/resources/META-INF/maven/lifecycle.xml
> +</lifecycles>
Please add a new line at the end of the file.

2023-09-11 18:21 UTC, pengyuejiang commented on emop-core/src/main/java/edu/cornell/emop/util/MethodsHelper.java
> +    }
Is there a better way to test these methods? One possible suggestion is using reflection.

2023-09-11 19:35 UTC, pengyuejiang requested changes
Just address these small comments. Thank you for the work!

2023-09-25 15:59 UTC, mmk-1 commented
Hello, I've addressed your comments, apologies for the delay!

2023-10-02 04:10 UTC, owolabileg commented on scripts/setup.sh
> +	      cd emop
minor: fix spacing of that cd command

2023-10-02 04:11 UTC, owolabileg commented
@pengyuejiang please comment quickly on this PR, just a quick "merge" or "no-merge" will do.

2023-10-14 14:26 UTC, merged